In [1]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /opt/anaconda3/lib/python3.12/site-packages (from ucimlrepo) (2024.7.4)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [3]:
from ucimlrepo import fetch_ucirepo

In [5]:
cdc_diabetes_health_indicators = fetch_ucirepo(id=891)

In [7]:
X = cdc_diabetes_health_indicators.data.features

In [9]:
X.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4

In [11]:
cdc_diabetes_health_indicators.keys()

dict_keys(['data', 'metadata', 'variables'])

<table class="table my-4 w-full"><thead><tr><th>Variable Name</th><th>Role</th><th>Type</th><th>Demographic</th><th>Description</th><th>Units</th><th>Missing Values</th></tr></thead> <tbody><tr><td>ID</td><td>ID</td><td>Integer</td><td></td><td>Patient ID</td><td></td><td>no</td> </tr><tr><td>Diabetes_binary</td><td>Target</td><td>Binary</td><td></td><td>0 = no diabetes 1 = prediabetes or diabetes</td><td></td><td>no</td> </tr><tr><td>HighBP</td><td>Feature</td><td>Binary</td><td></td><td>0 = no high BP 1 = high BP</td><td></td><td>no</td> </tr><tr><td>HighChol</td><td>Feature</td><td>Binary</td><td></td><td>0 = no high cholesterol 1 = high cholesterol</td><td></td><td>no</td> </tr><tr><td>CholCheck</td><td>Feature</td><td>Binary</td><td></td><td>0 = no cholesterol check in 5 years 1 = yes cholesterol check in 5 years</td><td></td><td>no</td> </tr><tr><td>BMI</td><td>Feature</td><td>Integer</td><td></td><td>Body Mass Index</td><td></td><td>no</td> </tr><tr><td>Smoker</td><td>Feature</td><td>Binary</td><td></td><td>Have you smoked at least 100 cigarettes in your entire life? [Note: 5 packs = 100 cigarettes] 0 = no 1 = yes</td><td></td><td>no</td> </tr><tr><td>Stroke</td><td>Feature</td><td>Binary</td><td></td><td>(Ever told) you had a stroke. 0 = no 1 = yes</td><td></td><td>no</td> </tr><tr><td>HeartDiseaseorAttack</td><td>Feature</td><td>Binary</td><td></td><td>coronary heart disease (CHD) or myocardial infarction (MI) 0 = no 1 = yes</td><td></td><td>no</td> </tr><tr><td>PhysActivity</td><td>Feature</td><td>Binary</td><td></td><td>physical activity in past 30 days - not including job 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>Sex</td><td>Feature</td><td>Binary</td><td>Sex</td><td>0 = female 1 = male</td><td></td><td>no</td> </tr>
<tr><td>DiffWalk</td><td>Feature</td><td>Binary</td><td></td><td>Do you have serious difficulty walking or climbing stairs? 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>PhysHlth</td><td>Feature</td><td>Integer</td><td></td><td>Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good? scale 1-30 days</td><td></td><td>no</td> </tr>
<tr><td>MentHlth</td><td>Feature</td><td>Integer</td><td></td><td>Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good? scale 1-30 days</td><td></td><td>no</td> </tr>
<tr><td>GenHlth</td><td>Feature</td><td>Integer</td><td></td><td>Would you say that in general your health is: scale 1-5 1 = excellent 2 = very good 3 = good 4 = fair 5 = poor</td><td></td><td>no</td> </tr>
<tr><td>NoDocbcCost</td><td>Feature</td><td>Binary</td><td></td><td>Was there a time in the past 12 months when you needed to see a doctor but could not because of cost? 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>AnyHealthcare</td><td>Feature</td><td>Binary</td><td></td><td>Have any kind of health care coverage, including health insurance, prepaid plans such as HMO, etc. 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>HvyAlcoholConsump</td><td>Feature</td><td>Binary</td><td></td><td>Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>Veggies</td><td>Feature</td><td>Binary</td><td></td><td>Consume Vegetables 1 or more times per day 0 = no 1 = yes</td><td></td><td>no</td> </tr>
<tr><td>Fruits</td><td>Feature</td><td>Binary</td><td></td><td>Consume Fruit 1 or more times per day 0 = no 1 = yes</td><td></td><td>no</td> </tr>
    <tr><td>Age</td><td>Feature</td><td>Integer</td><td>Age</td><td>13-level age category (_AGEG5YR see codebook) 1 = 18-24 9 = 60-64 13 = 80 or older</td><td></td><td>no</td> </tr>
<tr><td>Education</td><td>Feature</td><td>Integer</td><td>Education Level</td><td>Education level (EDUCA see codebook) scale 1-6 1 = Never attended school or only kindergarten 2 = Grades 1 through 8 (Elementary) 3 = Grades 9 through 11 (Some high school) 4 = Grade 12 or GED (High school graduate) 5 = College 1 year to 3 years (Some college or technical school) 6 = College 4 years or more (College graduate)</td><td></td><td>no</td> </tr>
<tr><td>Income</td><td>Feature</td><td>Integer</td><td>Income</td><td>Income scale (INCOME2 see codebook) scale 1-8 1 = less than $10,000 5 = less than $35,000 8 = $75,000 or more</td><td></td><td>no</td> </tr>
</tbody></table>

In [19]:
X.head()

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1,1,1,40,1,0,0,0,0,1,...,1,0,5,18,15,1,0,9,4,3
1,0,0,0,25,1,0,0,1,0,0,...,0,1,3,0,0,0,0,7,6,1
2,1,1,1,28,0,0,0,0,1,0,...,1,1,5,30,30,1,0,9,4,8
3,1,0,1,27,0,0,0,1,1,1,...,1,0,2,0,0,0,0,11,3,6
4,1,1,1,24,0,0,0,1,1,1,...,1,0,2,3,0,0,0,11,5,4